// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#import "DBTestJavaAbstractClassOnly.h"
#import <Foundation/Foundation.h>


@interface DBExternJavaAbstractClassOnly : NSObject

- (nullable DBTestJavaAbstractClassOnly *)foo:(nullable DBTestJavaAbstractClassOnly *)i;

@end
