// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "extern_java_abstract_class_only.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBExternJavaAbstractClassOnly;

namespace djinni_generated {

class ExternJavaAbstractClassOnly
{
public:
    using CppType = std::shared_ptr<::testsuite::ExternJavaAbstractClassOnly>;
    using CppOptType = std::shared_ptr<::testsuite::ExternJavaAbstractClassOnly>;
    using ObjcType = DBExternJavaAbstractClassOnly*;

    using Boxed = ExternJavaAbstractClassOnly;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

