// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#import "DBTestJavaInterfaceOnly.h"
#import <Foundation/Foundation.h>


@interface DBExternJavaInterfaceOnly : NSObject

- (nullable DBTestJavaInterfaceOnly *)foo:(nullable DBTestJavaInterfaceOnly *)i;

@end
