// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "extern_java_interface_only.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBExternJavaInterfaceOnly;

namespace djinni_generated {

class ExternJavaInterfaceOnly
{
public:
    using CppType = std::shared_ptr<::testsuite::ExternJavaInterfaceOnly>;
    using CppOptType = std::shared_ptr<::testsuite::ExternJavaInterfaceOnly>;
    using ObjcType = DBExternJavaInterfaceOnly*;

    using Boxed = ExternJavaInterfaceOnly;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

