// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public interface ExternJavaInterfaceOnly {
    @CheckForNull
    com.dropbox.djinni.test.TestJavaInterfaceOnly foo(@CheckForNull com.dropbox.djinni.test.TestJavaInterfaceOnly i);
}
