// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "djinni_support.hpp"
#include "extern_java_abstract_class_only.hpp"

namespace djinni_generated {

class NativeExternJavaAbstractClassOnly final : ::djinni::JniInterface<::testsuite::ExternJavaAbstractClassOnly, NativeExternJavaAbstractClassOnly> {
public:
    using CppType = std::shared_ptr<::testsuite::ExternJavaAbstractClassOnly>;
    using CppOptType = std::shared_ptr<::testsuite::ExternJavaAbstractClassOnly>;
    using JniType = jobject;

    using Boxed = NativeExternJavaAbstractClassOnly;

    ~NativeExternJavaAbstractClassOnly();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeExternJavaAbstractClassOnly>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeExternJavaAbstractClassOnly>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeExternJavaAbstractClassOnly();
    friend ::djinni::JniClass<NativeExternJavaAbstractClassOnly>;
    friend ::djinni::JniInterface<::testsuite::ExternJavaAbstractClassOnly, NativeExternJavaAbstractClassOnly>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::testsuite::ExternJavaAbstractClassOnly
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        /*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> foo(const /*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> & i) override;

    private:
        friend ::djinni::JniInterface<::testsuite::ExternJavaAbstractClassOnly, ::djinni_generated::NativeExternJavaAbstractClassOnly>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ExternJavaAbstractClassOnly") };
    const jmethodID method_foo { ::djinni::jniGetMethodID(clazz.get(), "foo", "(Lcom/dropbox/djinni/test/TestJavaAbstractClassOnly;)Lcom/dropbox/djinni/test/TestJavaAbstractClassOnly;") };
};

}  // namespace djinni_generated
