// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "NativeExternJavaAbstractClassOnly.hpp"  // my header
#include "NativeTestJavaAbstractClassOnly.hpp"

namespace djinni_generated {

NativeExternJavaAbstractClassOnly::NativeExternJavaAbstractClassOnly() : ::djinni::JniInterface<::testsuite::ExternJavaAbstractClassOnly, NativeExternJavaAbstractClassOnly>() {}

NativeExternJavaAbstractClassOnly::~NativeExternJavaAbstractClassOnly() = default;

NativeExternJavaAbstractClassOnly::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeExternJavaAbstractClassOnly::JavaProxy::~JavaProxy() = default;

/*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> NativeExternJavaAbstractClassOnly::JavaProxy::foo(const /*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> & c_i) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeExternJavaAbstractClassOnly>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_foo,
                                         ::djinni::get(::djinni_generated::NativeTestJavaAbstractClassOnly::fromCpp(jniEnv, c_i)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeTestJavaAbstractClassOnly::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
