// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "NativeExternJavaInterfaceOnly.hpp"  // my header
#include "NativeTestJavaInterfaceOnly.hpp"

namespace djinni_generated {

NativeExternJavaInterfaceOnly::NativeExternJavaInterfaceOnly() : ::djinni::JniInterface<::testsuite::ExternJavaInterfaceOnly, NativeExternJavaInterfaceOnly>() {}

NativeExternJavaInterfaceOnly::~NativeExternJavaInterfaceOnly() = default;

NativeExternJavaInterfaceOnly::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeExternJavaInterfaceOnly::JavaProxy::~JavaProxy() = default;

/*not-null*/ std::shared_ptr<::testsuite::TestJavaInterfaceOnly> NativeExternJavaInterfaceOnly::JavaProxy::foo(const /*not-null*/ std::shared_ptr<::testsuite::TestJavaInterfaceOnly> & c_i) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeExternJavaInterfaceOnly>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_foo,
                                         ::djinni::get(::djinni_generated::NativeTestJavaInterfaceOnly::fromCpp(jniEnv, c_i)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeTestJavaInterfaceOnly::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
