// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "djinni_support.hpp"
#include "extern_java_interface_only.hpp"

namespace djinni_generated {

class NativeExternJavaInterfaceOnly final : ::djinni::JniInterface<::testsuite::ExternJavaInterfaceOnly, NativeExternJavaInterfaceOnly> {
public:
    using CppType = std::shared_ptr<::testsuite::ExternJavaInterfaceOnly>;
    using CppOptType = std::shared_ptr<::testsuite::ExternJavaInterfaceOnly>;
    using JniType = jobject;

    using Boxed = NativeExternJavaInterfaceOnly;

    ~NativeExternJavaInterfaceOnly();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeExternJavaInterfaceOnly>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeExternJavaInterfaceOnly>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeExternJavaInterfaceOnly();
    friend ::djinni::JniClass<NativeExternJavaInterfaceOnly>;
    friend ::djinni::JniInterface<::testsuite::ExternJavaInterfaceOnly, NativeExternJavaInterfaceOnly>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::testsuite::ExternJavaInterfaceOnly
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        /*not-null*/ std::shared_ptr<::testsuite::TestJavaInterfaceOnly> foo(const /*not-null*/ std::shared_ptr<::testsuite::TestJavaInterfaceOnly> & i) override;

    private:
        friend ::djinni::JniInterface<::testsuite::ExternJavaInterfaceOnly, ::djinni_generated::NativeExternJavaInterfaceOnly>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ExternJavaInterfaceOnly") };
    const jmethodID method_foo { ::djinni::jniGetMethodID(clazz.get(), "foo", "(Lcom/dropbox/djinni/test/TestJavaInterfaceOnly;)Lcom/dropbox/djinni/test/TestJavaInterfaceOnly;") };
};

}  // namespace djinni_generated
