// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#pragma once

#include "test_java_abstract_class_only.hpp"
#include <memory>

namespace testsuite {

class ExternJavaAbstractClassOnly {
public:
    virtual ~ExternJavaAbstractClassOnly() = default;

    virtual /*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> foo(const /*not-null*/ std::shared_ptr<::testsuite::TestJavaAbstractClassOnly> & i) = 0;
};

}  // namespace testsuite
